# Generated by Django 5.2.4 on 2025-08-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicare', '0002_jobopening_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark this product as featured for the homepage modal'),
        ),
    ]
