# Generated by Django 5.2.6 on 2025-09-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicare', '0003_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_location',
            field=models.CharField(blank=True, help_text='Delivery address for the order', max_length=200),
        ),
    ]
